// graph_wave_amplitude_amplification_contract_test
// ----------------------------------------------------------------------------
// One question: can the linear graph-wave substrate make a DECISION natively --
// concentrate probability onto a chosen node -- using only interference, with
// no argmax, no iteration-as-training, no GA, no nonlinearity in the field?
//
// This continues the superposition-as-computation thread. The previous contract
// showed the Born readout turns superposition into a nonlinear, phase-carrying
// computation. Here the same coherence is steered: a target node is MARKED with
// a purely local phase (a gauge / on-site potential pulse, invisible to |psi|^2
// on its own), and then the field is reflected on the all-to-all medium. The two
// linear, unitary operations interfere so that amplitude piles up on the marked
// node -- amplitude amplification (one Grover iteration), the native decision
// primitive.
//
// * oracle O = I - 2|t><t| == a pi gauge/on-site phase on the target node
// * diffuse D = 2|s><s| - I == reflection generated by the complete-graph
// (uniform all-to-all) wave medium
//
// Substrate only, exact unitaries (the ideal limits of those evolutions).
// types, no trainer, no decision path wired anywhere.
// ----------------------------------------------------------------------------

#include <algorithm>
#include <cmath>
#include <complex>
#include <cstdio>
#include <vector>

namespace {

using cd = std::complex<double>;
using Vec = std::vector<cd>;

constexpr int kN = 16; // 1/sqrt(N) = 1/4 exactly
constexpr int kTarget = 5;
constexpr int kRetarget = 11;

double norm2(const Vec& z) {
 double s = 0.0;
 for (const auto& v : z) s += std::norm(v);
 return s;
}

Vec uniform() { return Vec(kN, cd(1.0 / std::sqrt(static_cast<double>(kN)), 0.0)); }

// Mark a node with a local pi phase: O = I - 2|t><t|. Pure on-site gauge phase.
Vec oracle(Vec z, const int t) { z[t] = -z[t]; return z; }

// Reflect about the uniform mode on the complete-graph medium: D = 2|s><s| - I.
Vec diffuse(const Vec& z) {
 cd mean(0, 0);
 for (const auto& v : z) mean += v;
 mean /= static_cast<double>(kN);
 Vec out(kN);
 for (int i = 0; i < kN; ++i) out[i] = 2.0 * mean - z[i];
 return out;
}

Vec groverStep(const Vec& z, const int t) { return diffuse(oracle(z, t)); }

double probAt(const Vec& z, const int i) { return std::norm(z[i]); }

int argmaxProb(const Vec& z) {
 int best = 0;
 double bp = -1.0;
 for (int i = 0; i < kN; ++i) {
 const double p = std::norm(z[i]);
 if (p > bp) { bp = p; best = i; }
 }
 return best;
}

bool report(const char* name, const bool ok) {
 std::printf(" => %s\n", ok ? "PASS" : "FAIL");
 if (!ok) std::printf(" !! %s\n", name);
 return ok;
}

} // namespace

int main() {
 std::printf("=====================================================================\n");
 std::printf(" GRAPH-WAVE AMPLITUDE AMPLIFICATION CONTRACT TEST\n");
 std::printf(" Interference concentrates probability on a marked node (N=%d).\n", kN);
 std::printf("=====================================================================\n");
 const double uniformP = 1.0 / static_cast<double>(kN);
 std::printf(" uniform per-node probability = %.6f\n", uniformP);

 int pass = 0;
 int total = 0;

 // [1] THE BUILDING BLOCKS ARE NORM-PRESERVING (unitary) ------------------
 std::printf("\n[1] ORACLE AND DIFFUSION ARE NORM-PRESERVING\n");
 {
 const Vec s = uniform();
 const double n0 = norm2(s);
 const double nOracle = norm2(oracle(s, kTarget));
 const double nDiffuse = norm2(diffuse(s));
 const double nStep = norm2(groverStep(s, kTarget));
 std::printf(" norm: start=%.15f oracle=%.15f diffuse=%.15f step=%.15f\n",
 n0, nOracle, nDiffuse, nStep);
 const double err = std::max({std::abs(nOracle - 1.0), std::abs(nDiffuse - 1.0),
 std::abs(nStep - 1.0)});
 ++total; pass += report("a building block is not unitary", err < 1e-12);
 }

 // [2] THE MARK IS A PURE LOCAL PHASE, INVISIBLE TO |psi|^2 ALONE ----------
 std::printf("\n[2] THE ORACLE MARK IS A PURE LOCAL PHASE (no decision visible yet)\n");
 {
 const Vec s = uniform();
 const Vec marked = oracle(s, kTarget);
 double maxProbDiff = 0.0;
 for (int i = 0; i < kN; ++i)
 maxProbDiff = std::max(maxProbDiff, std::abs(probAt(marked, i) - probAt(s, i)));
 std::printf(" max per-node |psi|^2 change from the mark = %.2e\n", maxProbDiff);
 // The decision is latent in phase: magnitudes are untouched until diffusion.
 ++total; pass += report("marking changed magnitudes (not a pure phase)",
 maxProbDiff < 1e-15);
 }

 // [3] ONE INTERFERENCE STEP CONCENTRATES PROBABILITY ON THE MARK ----------
 std::printf("\n[3] ONE STEP CONCENTRATES PROBABILITY ON THE MARKED NODE\n");
 {
 const Vec out = groverStep(uniform(), kTarget);
 const double pTarget = probAt(out, kTarget);
 const int winner = argmaxProb(out);
 const double analytic = 121.0 / 256.0; // sin^2(3*asin(1/4)) = (11/16)^2
 double pOther = 0.0;
 for (int i = 0; i < kN; ++i) if (i != kTarget) pOther = std::max(pOther, probAt(out, i));
 std::printf(" P(target)=%.6f analytic=%.6f best_other=%.6f\n",
 pTarget, analytic, pOther);
 std::printf(" amplification vs uniform = %.2fx winner node = %d (target=%d)\n",
 pTarget / uniformP, winner, kTarget);
 const bool matches = std::abs(pTarget - analytic) < 1e-9;
 const bool amplified = pTarget / uniformP > 4.0;
 const bool uniqueWinner = (winner == kTarget) && (pTarget > pOther + 0.1);
 ++total; pass += report("one step did not concentrate on the marked node",
 matches && amplified && uniqueWinner);
 }

 // [4] THE WINNER IS PROGRAMMABLE BY THE PHASE PATTERN (the "weights") -----
 std::printf("\n[4] THE DECISION IS PROGRAMMABLE: RE-MARK MOVES THE WINNER\n");
 {
 const Vec out = groverStep(uniform(), kRetarget);
 const int winner = argmaxProb(out);
 const double pNew = probAt(out, kRetarget);
 std::printf(" re-marked node %d -> winner=%d P=%.6f\n", kRetarget, winner, pNew);
 ++total; pass += report("winner did not follow the re-mark",
 winner == kRetarget && std::abs(pNew - 121.0 / 256.0) < 1e-9);
 }

 // [5] AMPLIFICATION ACCUMULATES OVER STEPS (genuine, not a one-off) -------
 std::printf("\n[5] AMPLIFICATION ACCUMULATES OVER STEPS\n");
 {
 Vec z = uniform();
 double p1 = 0.0, p3 = 0.0;
 for (int k = 1; k <= 3; ++k) {
 z = groverStep(z, kTarget);
 const double p = probAt(z, kTarget);
 if (k == 1) p1 = p;
 if (k == 3) p3 = p;
 std::printf(" after step %d: P(target)=%.6f\n", k, p);
 }
 ++total; pass += report("amplification did not accumulate", p3 > p1 && p3 > 0.9);
 }

 std::printf("\n RESULT : %d / %d verified\n", pass, total);
 return pass == total ? 0 : 1;
}
