// graph_wave_hypercube_gate_contract_test  (PHYSICS-ONLY)
// ----------------------------------------------------------------------------
// THE GATE BASELINE, generated by the substrate and read by populations only.
// The n-qubit register lives on a HYPERCUBE (2^n nodes, an edge between indices
// differing in one bit). A single-bit-flip EDGE evolved by gw::Stepper IS a
// single-qubit rotation; the two-qubit ENTANGLER is a different ingredient -- a
// diagonal gauge-flux term on a multi-bit node -- also GROWN by gw::Stepper, never
// posited by hand. Everything is read by the Born rule (qubit_physics.hpp).
//
// One question: is the hypercube a faithful gate substrate?
//   [1] a single-bit edge rotates exactly ONE qubit (its <Z> -> 0, lands on the
//       equator, stays pure) and leaves every other qubit's <Z> untouched.
//   [2] single-qubit gates NEVER entangle: rotate all qubits -> max entropy 0.
//   [3] a physical flux-CZ (an evolved diagonal pi-flux) entangles |+>|+> -> ln2.
// Substrate-only, deterministic. No weights, no trainer.
// ----------------------------------------------------------------------------
#include "qubit_physics.hpp"

#include <cmath>
#include <cstdio>

namespace {
using gw::Vec;
const double kLn2 = std::log(2.0);
bool report(const char* w, bool ok) { std::printf("   => %s\n", ok ? "PASS" : "FAIL"); if (!ok) std::printf("   !! %s\n", w); return ok; }
} // namespace

int main() {
 std::printf("=====================================================================\n");
 std::printf(" GRAPH-WAVE HYPERCUBE GATE CONTRACT (physics-only)\n");
 std::printf(" Single-bit EDGE = single-qubit gate; diagonal FLUX = entangler.\n");
 std::printf("=====================================================================\n");
 int pass = 0, total = 0;
 const double czDt = 2.0 * std::tan(qp::kPi / 64.0); const int czSteps = 32; // exact pi-flux CZ

 std::printf("\n[1] SINGLE-BIT EDGE ROTATES EXACTLY ONE QUBIT (others' <Z> untouched)\n");
 {
  const int n = 3; Vec f = qp::inject0(n);            // |000>: every <Z> = +1
  f = qp::edgeRotX(f, n, 1, qp::dtHalfPi());          // physical Rx(pi/2) on qubit 1 only
  const double z0 = qp::expectZ(f, n, 0), z1 = qp::expectZ(f, n, 1), z2 = qp::expectZ(f, n, 2);
  const double y1 = qp::expectY(f, n, 1), s1 = qp::entropyOf(f, n, 1);
  std::printf("   qubit 1 rotated: <Z>=%.3e (->0)  |<Y>|=%.12f (->1)  entropy=%.3e (pure)\n", z1, std::abs(y1), s1);
  std::printf("   qubit 0 <Z>=%.12f   qubit 2 <Z>=%.12f  (both still +1, untouched)\n", z0, z2);
  const bool ok = std::abs(z1) < 1e-12 && std::abs(std::abs(y1) - 1.0) < 1e-12 && s1 < 1e-9
                  && std::abs(z0 - 1.0) < 1e-12 && std::abs(z2 - 1.0) < 1e-12;
  ++total; pass += report("single-bit edge is not a localized single-qubit rotation", ok) ? 1 : 0;
 }

 std::printf("\n[2] SINGLE-QUBIT GATES NEVER ENTANGLE: rotate all -> max entropy 0\n");
 {
  const int n = 3; Vec f = qp::inject0(n);
  // distinct physical rotation angles per qubit (alpha = 4 arctan(dt/2))
  f = qp::edgeRotX(f, n, 0, 2.0 * std::tan(qp::kPi / 12.0));
  f = qp::edgeRotX(f, n, 1, 2.0 * std::tan(qp::kPi / 16.0));
  f = qp::edgeRotX(f, n, 2, 2.0 * std::tan(qp::kPi / 6.0));
  const double maxS = qp::maxEntropy(f, n);
  std::printf("   after distinct single-qubit rotations: max entropy = %.3e\n", maxS);
  ++total; pass += report("single-qubit gates produced entanglement", maxS < 1e-9) ? 1 : 0;
 }

 std::printf("\n[3] PHYSICAL FLUX-CZ ENTANGLES |+>|+> -> ln2 (grown by gw::Stepper)\n");
 {
  const int n = 2; Vec f = qp::inject0(n);
  f = qp::edgeRotX(f, n, 0, qp::dtHalfPi());
  f = qp::edgeRotX(f, n, 1, qp::dtHalfPi());           // |+>|+> (product)
  const double before = qp::maxEntropy(f, n);
  f = qp::fluxCZ(f, n, 0, 1, czDt, czSteps);           // physical CZ
  const double s0 = qp::entropyOf(f, n, 0), s1 = qp::entropyOf(f, n, 1);
  std::printf("   entropy before = %.3e ; after: qubit0=%.12f qubit1=%.12f (ln2=%.12f)\n", before, s0, s1, kLn2);
  const bool ok = before < 1e-9 && std::abs(s0 - kLn2) < 1e-9 && std::abs(s1 - kLn2) < 1e-9;
  ++total; pass += report("flux-CZ did not maximally entangle |+>|+>", ok) ? 1 : 0;
 }

 std::printf("\n=====================================================================\n");
 std::printf(" RESULT : %d / %d verified\n", pass, total);
 std::printf(" %s\n", pass == total
             ? "the hypercube is a faithful gate substrate (edges rotate, flux entangles) -- all physical"
             : "inspect the failing gate");
 std::printf("=====================================================================\n");
 return pass == total ? 0 : 1;
}
