// graph_wave_entanglement_dynamics_contract_test
// ----------------------------------------------------------------------------
// Grounds entanglement in real medium dynamics (as dynamic-bind did for
// binding): two qubit lanes coupled by an XY (hopping) interaction in the
// Hamiltonian, evolved by the suite's Cayley Stepper. Entanglement is GENERATED
// by the physics, not posited by an abstract gate:
//   [1] from a product start, the inter-lane coupling grows entanglement
//       entropy 0 -> ln2 (maximal at a quarter period).
//   [2] with the coupling OFF (local terms only) entropy stays 0 -- no
//       interaction, no entanglement.
//   [3] the evolution stays unitary (norm preserved).
//   [4] it is reversible: at the half period the excitation has fully swapped
//       and the state is a product again (entropy back to 0).
// Substrate-only, deterministic. No V26 linkage, no weights, no trainer.
// ----------------------------------------------------------------------------
#include <algorithm>
#include <cmath>
#include <complex>
#include <cstdio>
#include <utility>
#include <vector>
namespace {
using cd = std::complex<double>; using Vec = std::vector<cd>; using Mat = std::vector<std::vector<cd>>;
constexpr int kN = 4;          // 2 qubit lanes
double norm2(const Vec&z){double s=0;for(auto&v:z)s+=std::norm(v);return s;}
Vec matvec(const Mat&m,const Vec&z){Vec o(kN,cd(0,0));for(int i=0;i<kN;i++){cd s(0,0);for(int j=0;j<kN;j++)s+=m[i][j]*z[j];o[i]=s;}return o;}
void reduceFirst(const Vec&psi,cd r[2][2]){for(int i=0;i<2;i++)for(int j=0;j<2;j++){cd s(0,0);for(int b=0;b<2;b++)s+=psi[i*2+b]*std::conj(psi[j*2+b]);r[i][j]=s;}}
double entropy(const cd r[2][2]){double p=std::real(r[0][0]);double c=std::abs(r[0][1]);double d=std::sqrt((2*p-1)*(2*p-1)+4*c*c);double l1=0.5*(1+d),l2=0.5*(1-d);auto h=[](double l){return l>1e-12?-l*std::log(l):0.0;};return h(l1)+h(l2);}
struct LUC{int n=0;Mat a;std::vector<int>piv;void factor(Mat in){n=(int)in.size();a=std::move(in);piv.resize(n);for(int i=0;i<n;i++)piv[i]=i;for(int k=0;k<n;k++){double b=std::abs(a[k][k]);int r=k;for(int i=k+1;i<n;i++){double v=std::abs(a[i][k]);if(v>b){b=v;r=i;}}if(r!=k){std::swap(a[r],a[k]);std::swap(piv[r],piv[k]);}cd akk=a[k][k];for(int i=k+1;i<n;i++){cd f=a[i][k]/akk;a[i][k]=f;for(int j=k+1;j<n;j++)a[i][j]-=f*a[k][j];}}}Vec solve(const Vec&b)const{Vec x(n);for(int i=0;i<n;i++)x[i]=b[piv[i]];for(int i=0;i<n;i++){cd s=x[i];for(int j=0;j<i;j++)s-=a[i][j]*x[j];x[i]=s;}for(int i=n-1;i>=0;i--){cd s=x[i];for(int j=i+1;j<n;j++)s-=a[i][j]*x[j];x[i]=s/a[i][i];}return x;}};
struct Stepper{Mat am;LUC lu;void build(const Mat&h,double dt){Mat ap(kN,Vec(kN));am.assign(kN,Vec(kN));const cd I(0,1);for(int i=0;i<kN;i++)for(int j=0;j<kN;j++){cd k=I*h[i][j]*(dt/2.0);cd id=(i==j)?cd(1,0):cd(0,0);ap[i][j]=id+k;am[i][j]=id-k;}lu.factor(ap);}Vec evolve(Vec z,int s)const{for(int t=0;t<s;t++)z=lu.solve(matvec(am,z));return z;}};
double entOf(const Vec&p){cd r[2][2];reduceFirst(p,r);return entropy(r);}
bool report(const char*n,bool ok){std::printf("    => %s\n",ok?"PASS":"FAIL");if(!ok)std::printf("    !! %s\n",n);return ok;}
}
int main(){
  std::printf("=====================================================================\n");
  std::printf(" GRAPH-WAVE ENTANGLEMENT DYNAMICS CONTRACT TEST  (2 lanes, real Stepper)\n");
  std::printf(" Entanglement generated by an inter-lane coupling in the Hamiltonian.\n");
  std::printf("=====================================================================\n");
  const double J=1.0;
  // XY (hopping) coupling: H = J(XX+YY) = 2J(|01><10| + |10><01|)  (indices 1,2)
  Mat Hxy(kN,Vec(kN,cd(0,0)));Hxy[1][2]=cd(2*J,0);Hxy[2][1]=cd(2*J,0);
  // decoupled control: local Z fields only (diagonal) -> never entangles
  Mat Hloc(kN,Vec(kN,cd(0,0)));for(int i=0;i<kN;i++){int b0=(i>>1)&1,b1=i&1;Hloc[i][i]=cd((b0?-1:1)+(b1?-1:1),0);}
  Vec start={cd(0,0),cd(0,0),cd(1,0),cd(0,0)};  // |10> : excitation on lane A (product, S=0)
  const double kPi=3.141592653589793238;
  const double tQuarter=kPi/8.0, tHalf=kPi/4.0;  // 2J t = pi/4 and pi/2
  int pass=0,total=0;

  std::printf("\n[1] INTER-LANE COUPLING GROWS ENTANGLEMENT FROM A PRODUCT STATE\n");
  {std::printf("    start |10> entropy = %.6f\n",entOf(start));
   Stepper s;s.build(Hxy,tQuarter/2000);
   for(double frac:{0.25,0.5,0.75,1.0}){Vec z=s.evolve(start,(int)(2000*frac));std::printf("    2J t = %.3f*pi/4 : entropy = %.6f\n",frac,entOf(z));}
   Vec zq=s.evolve(start,2000);double sq=entOf(zq);
   ++total;pass+=report("coupling did not generate entanglement",entOf(start)<1e-9&&sq>0.69&&std::abs(sq-std::log(2.0))<0.01);}

  std::printf("\n[2] NO COUPLING (LOCAL TERMS ONLY) -> NO ENTANGLEMENT\n");
  {Stepper s;s.build(Hloc,tQuarter/2000);double mx=0;for(int k=1;k<=2000;k++){Vec z=s.evolve(start,k);mx=std::max(mx,entOf(z));}
   std::printf("    max entropy over the run = %.2e\n",mx);
   ++total;pass+=report("local-only evolution created entanglement",mx<1e-9);}

  std::printf("\n[3] EVOLUTION STAYS UNITARY (norm preserved)\n");
  {Stepper s;s.build(Hxy,tQuarter/2000);Vec z=s.evolve(start,2000);
   std::printf("    norm drift = %.2e\n",std::abs(norm2(z)-1.0));
   ++total;pass+=report("evolution not unitary",std::abs(norm2(z)-1.0)<1e-9);}

  std::printf("\n[4] REVERSIBLE: AT THE HALF PERIOD THE STATE IS A PRODUCT AGAIN\n");
  {Stepper s;s.build(Hxy,tHalf/4000);Vec z=s.evolve(start,4000);double sh=entOf(z);
   std::printf("    2J t = pi/2 : entropy = %.6f  (excitation fully swapped -> product)\n",sh);
   ++total;pass+=report("entanglement not reversible",sh<1e-3);}

  std::printf("\n RESULT : %d / %d verified\n",pass,total);return pass==total?0:1;
}
